# Generated by Django 4.2.4 on 2023-08-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryBuilderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.TextField(max_length=255)),
                ('Industry', models.TextField(max_length=255)),
                ('Year_Founded', models.DateField()),
                ('City', models.TextField(max_length=255)),
                ('State', models.TextField(max_length=255)),
                ('Country', models.TextField(max_length=255)),
                ('Employee_From', models.DateTimeField()),
                ('Employee_To', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
